[package]
name = "polybar_launch"
version = "0.1.0"
authors = ["Saphielle Akiyama <saphielle.akiyama@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
