[package]
name = "i3-scripts"
version = "0.1.0"
authors = ["Saphielle Akiyama <=>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4" 
